server:
  port: 8099
spring:
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
      routes:
        - id: ms-persistence
          uri: http://localhost:8081
          predicates:
            - Path=/customer/**
          filters:
            - PreFilter
            - PostFilter
  application:
    name: ms-apigateway
